services:
  endpoint:
    container_name: api_faculdade
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "45000:5000"
    restart: always
    networks:
      - proxy
    tty: true
    stdin_open: true

networks:
  proxy: